language: elixir
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.4
  - 1.8.0
notifications:
  recipients:
    - bruce.williams@cargosense.com
    - ben.wilson@cargosense.com
otp_release:
  - 19.3
  - 20.3
  - 21.2
matrix:
  exclude:
    - otp_release: 21.2
      elixir: 1.4.5
    - otp_release: 21.2
      elixir: 1.5.3
    - otp_release: 19.3
      elixir: 1.8.0
script: "MIX_ENV=test mix local.hex --force && MIX_ENV=test mix do deps.get, test"
